name: GCC & G++
on:
  push:
    branches:
    - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: g++ install
      run: sudo apt install gcc g++ make -y
    - name: g++ build
      run: g++ main.cpp -o main.out -Wall -Wextra -std=c++11
    - name: run
      run: ./main.out
    - name: gcc build
      run: gcc main.cpp -o main2.out -Wall -Wextra -std=c++11
    - name: run
      run: ./main2.out
