name: GCC

on:
  push:
    branches:
    - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt install gcc g++ make -y
    - name: build
      run: g++ main.cpp -o main.out -Wall -Wextra -std=c++11
    - name: run
      run: ./main.out
